version: '2.1'

services:
  002-docker-vscode:
    image: 002-docker-vscode
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js